import { test, expect } from "@playwright/test";
import { randomBytes } from "crypto";

// We specifically want to target the Cloudflare environment
// Default to staging if available, or production if explicitly testing live
const CLOUD_API = process.env.VITE_CLOUD_API_URL || "https://management-hub.clickflash-office.workers.dev";
const MOCK_DESK_ID = `test_desk_${Date.now()}`;

// Mock JWT Token structure expected by cloudflare worker
// In a real scenario, this would be generated by logging in as a master node
// For these tests, we rely on the `desk_id` or mock auth payloads. 
// Note: Many of the sync endpoints extract desk_id directly from the payload.
const MOCK_AUTH_HEADERS = {
    // If the endpoint strictly requires a valid JWT, we might need to mock login first
    // For now, we simulate what the CloudSyncService sends.
    "Content-Type": "application/json"
};

/**
 * End-to-End Tests for Cloudflare Worker Backend Integration
 * These tests verify the cloud syncing, R2 upload endpoints, and bidirectional operation handling.
 */

test.describe("Master to Cloudflare Integration", () => {
    
    // 1. Settings & Heartbeat
    test("should successfully sync global settings", async ({ request }) => {
        // GET /api/cloud/sync/settings
        // Requires auth, we'll try it. If it fails due to auth, we'll need to fetch a real token via login.
        
        // Let's first test the health endpoint which is public
        const healthRes = await request.get(`${CLOUD_API}/api/health`);
        expect(healthRes.status()).toBe(200);
        const healthBody = await healthRes.json();
        expect(healthBody.status).toBe("ok");
    });

    test("should reject unauthenticated heartbeat", async ({ request }) => {
        const res = await request.post(`${CLOUD_API}/api/cloud/heartbeat`, {
            data: { desk_id: MOCK_DESK_ID, timestamp: new Date().toISOString() }
        });
        
        // Expected to fail because we are not passing a valid JWT
        expect(res.status()).toBe(401); 
    });

    // To do authenticated tests, we need a valid JWT. 
    // We will simulate logging in as our test admin user to get a token for the rest of the tests.
    let authToken = "";

    test.beforeAll(async ({ request }) => {
        // We created this user specifically for testing in D1
        const loginRes = await request.post(`${CLOUD_API}/api/auth/login`, {
            data: {
                email: "alaeddine@example.com",
                password: "Admin123!",
                system_info: {
                    type: "E2E_Test_Runner",
                    machine_id: MOCK_DESK_ID
                }
            }
        });

        if (loginRes.ok()) {
            const data = await loginRes.json();
            authToken = data.token;
        } else {
            const body = await loginRes.text();
            console.error(`Failed to acquire auth token for Cloudflare tests. Status: ${loginRes.status()}, Body: ${body}`);
        }
    });

    test("should accept authenticated heartbeat", async ({ request }) => {
        test.skip(!authToken, "No auth token available");

        const res = await request.post(`${CLOUD_API}/api/cloud/heartbeat`, {
            headers: {
                "Authorization": `Bearer ${authToken}`,
                "Content-Type": "application/json"
            },
            data: {
                desk_id: MOCK_DESK_ID,
                timestamp: new Date().toISOString(),
                metrics: { cpu: 10, memory: 50 }
            }
        });

        if (!res.ok()) {
            const errBody = await res.text();
            console.error(`Heartbeat failed: ${errBody}`);
        }
        expect(res.status()).toBe(200);
        const body = await res.json();
        expect(body.success).toBe(true);
    });

    // 2. Order Sync
    test("should sync an order and generate magic link", async ({ request }) => {
        test.skip(!authToken, "No auth token available");

        const orderId = `ord_e2e_${Date.now()}`;
        
        const res = await request.post(`${CLOUD_API}/api/cloud/sync/order`, {
            headers: {
                "Authorization": `Bearer ${authToken}`,
                "Content-Type": "application/json"
            },
            data: {
                desk_id: MOCK_DESK_ID,
                order: {
                    id: orderId,
                    email: "test_customer@clickflash.com",
                    clientName: "E2E Customer",
                    status: "paid",
                    fulfillment_status: "synced",
                    total: 100,
                    totalAmount: 100,
                    items: []
                }
            }
        });

        expect(res.status()).toBe(200);
        const body = await res.json();
        expect(body.success).toBe(true);
        expect(body.orderId).toBe(orderId);
        // Ensure access_pin was generated by the cloudflare worker
        expect(body.accessPin).toBeTruthy(); 
    });

    // 3. Bi-directional Operations
    test("should handle bi-directional operation sync", async ({ request }) => {
        test.skip(!authToken, "No auth token available");

        const operationId = `op_e2e_${Date.now()}`;
        
        // Push an operation
        const pushRes = await request.post(`${CLOUD_API}/api/cloud/sync/operations`, {
            headers: {
                "Authorization": `Bearer ${authToken}`,
                "Content-Type": "application/json"
            },
            data: {
                desk_id: MOCK_DESK_ID,
                operations: [{
                    id: operationId,
                    type: "insert",
                    table: "test_table",
                    record_id: "rec_123",
                    payload: { foo: "bar" },
                    timestamp: new Date().toISOString(),
                    sequence_number: 1
                }]
            }
        });

        expect(pushRes.status()).toBe(200);
        const pushBody = await pushRes.json();
        expect(pushBody.success).toBe(true);
        expect(pushBody.processed).toContain(operationId);

        // Pull operations
        const pullRes = await request.get(`${CLOUD_API}/api/cloud/sync/operations?since_hub_index=0`, {
            headers: {
                "Authorization": `Bearer ${authToken}`,
            }
        });

        expect(pullRes.status()).toBe(200);
        const pullBody = await pullRes.json();
        expect(pullBody.success).toBe(true);
        expect(Array.isArray(pullBody.operations)).toBe(true);
    });

    // 4. Photo Upload to R2
    test("should support chunked photo uploads to R2", async ({ request }) => {
        test.skip(!authToken, "No auth token available");

        const photoId = `photo_e2e_${Date.now()}`;
        const buffer = randomBytes(1024); // 1KB dummy file

        // Use multipart/form-data for chunk upload
        const res = await request.post(`${CLOUD_API}/api/cloud/upload-photo/chunk`, {
            headers: {
                "Authorization": `Bearer ${authToken}`
            },
            multipart: {
                deskId: MOCK_DESK_ID,
                albumId: "album_e2e",
                photoId: photoId,
                originalName: "test_image.jpg",
                chunkIndex: "0",
                totalChunks: "1",
                file: {
                    name: "test_image.jpg",
                    mimeType: "image/jpeg",
                    buffer: buffer
                }
            }
        });

        expect(res.status()).toBe(200);
        const body = await res.json();
        expect(body.success).toBe(true);
        // Expecting R2 key to be constructed correctly
        expect(body.key).toBe(`${MOCK_DESK_ID}/album_e2e/test_image.jpg`);
    });
});
