
import { AppRole, Permission } from './types';

// Define all possible permissions in the application
export const ALL_PERMISSIONS: Permission[] = [
    // Master Portal
    'viewDashboard',
    'viewAlbums',
    'manageOwnAlbums',
    'manageAllAlbums',
    'viewOrders',
    'viewOwnOrders',
    'viewAllOrders',
    'viewPhotographers',
    'managePhotographers',
    'viewBookings',
    'manageBookings',
    'viewSettings',
    'manageLocalSettings',
    'manageSessionTypes',
    'viewProducts',
    'manageProducts',
    // Management Portal Permissions
    'viewManagementDashboard',
    'viewDestinations',
    'viewReports',
    'viewExpenses',
    'viewCapital',
    'viewAdjustments',
    'manageAdjustments',
    'viewPerformance',
    'viewWarehouse',
    'manageEquipmentCategories',
    'viewPayroll',
    'runPayroll',
    'viewEcommerceSettings',
    'viewGlobalSettings',
    'manageGlobalSettings',
    'viewDocumentation',
    'manageExpenseCategories',
    'viewMonitoring',
    'viewRevenue',
    'manageWebsite',
    'manageSystemInfrastructure'
];

// Map roles to their permissions
export const PERMISSIONS: Record<AppRole, Permission[]> = {
    Photographer: [
        'viewDashboard',
        'viewAlbums',
        'manageOwnAlbums',
        'viewOrders',
        'viewOwnOrders',
        'viewBookings',
        'viewDocumentation',
        'viewProducts',
    ],
    'Team Leader': [
        'viewDashboard',
        'viewAlbums',
        'manageAllAlbums',
        'viewOrders',
        'viewAllOrders',
        'viewPhotographers',
        'viewBookings',
        'manageBookings',
        'viewSettings',
        'manageLocalSettings',
        'manageSessionTypes',
        'viewDocumentation',
        'viewProducts',
        'manageProducts',
    ],
    Admin: [
        // Master Portal Permissions
        'viewDashboard',
        'viewAlbums',
        'manageOwnAlbums',
        'manageAllAlbums',
        'viewOrders',
        'viewOwnOrders',
        'viewAllOrders',
        'viewPhotographers',
        'managePhotographers',
        'viewBookings',
        'manageBookings',
        'viewSettings',
        'manageLocalSettings',
        'manageSessionTypes',
        'viewDocumentation',
        'viewProducts',
        'manageProducts',
        // Management Portal Permissions
        'viewManagementDashboard',
        'viewDestinations',
        'viewReports',
        'viewExpenses',
        'viewCapital',
        'viewAdjustments',
        'manageAdjustments',
        'viewPerformance',
        'viewWarehouse',
        'viewPayroll',
        'runPayroll',
        'viewEcommerceSettings',
        'viewGlobalSettings',
        'manageGlobalSettings',
        'manageExpenseCategories',
        'manageEquipmentCategories',
        'viewMonitoring',
        'viewRevenue',
        'manageWebsite',
        'manageSystemInfrastructure'
    ],
    Manager: [ // Manager role for the Management Portal
        'viewManagementDashboard',
        'viewDestinations',
        'viewReports',
        'viewExpenses',
        'viewCapital',
        'viewAdjustments',
        'manageAdjustments',
        'viewPerformance',
        'viewWarehouse',
        'viewPayroll',
        'runPayroll',
        'viewEcommerceSettings',
        'viewGlobalSettings',
        'manageGlobalSettings',
        'manageExpenseCategories',
        'manageEquipmentCategories',
        'manageSessionTypes',
        'viewDocumentation',
        // Also give them master portal permissions for viewing and emergency local management
        'viewDashboard',
        'viewAlbums',
        'viewOrders',
        'viewPhotographers',
        'viewBookings',
        'viewSettings',
        'manageLocalSettings',
        'viewProducts',
        'manageProducts',
        'viewMonitoring',
        'viewRevenue',
        'manageWebsite',
        'manageSystemInfrastructure',
    ],
    CEO: [
        ...ALL_PERMISSIONS,
    ],
    "HQ Admin": [
        ...ALL_PERMISSIONS,
    ],
    "Regional Manager": [
        'viewManagementDashboard',
        'viewDestinations',
        'viewReports',
        'viewExpenses',
        'viewPerformance',
        'viewWarehouse',
        'viewPayroll',
        'viewRevenue',
    ],
    "Resort Manager": [
        'viewManagementDashboard',
        'viewDestinations',
        'viewReports',
        'viewPerformance',
        'viewWarehouse',
        'viewDashboard',
        'viewAlbums',
        'viewOrders',
        'viewPhotographers',
        'viewBookings',
        'viewSettings',
        'manageLocalSettings',
        'viewProducts',
    ],
    admin: [
        ...ALL_PERMISSIONS,
    ],
    manager: [
        'viewManagementDashboard',
        'viewDestinations',
        'viewReports',
    ],
    photographer: [
        'viewDashboard',
        'viewAlbums',
    ],
    editor: [
        'viewDashboard',
        'viewAlbums',
    ],
    support: [
        'viewDashboard',
    ],
};


// Helper function to check permissions
export function hasPermission(role: AppRole, permission: Permission): boolean {
    return PERMISSIONS[role]?.includes(permission) || false;
}