export const getEnv = (env: any) => {
  const jwtSecret = env.JWT_SECRET;
  if (!jwtSecret) {
    throw new Error('FATAL: JWT_SECRET environment variable is required. Cannot start without secure JWT secret.');
  }
  
  return {
    PORT: env.PORT || "8787",
    JWT_SECRET: jwtSecret,
    ALLOWED_ORIGINS: env.ALLOWED_ORIGINS
      ? env.ALLOWED_ORIGINS.split(",").map((o: string) => o.trim())
      : [
          "http://localhost:5173",
          "http://localhost:8000",
          "http://127.0.0.1:5173",
        ],
  };
};

export const TABLE_MAP: Record<string, string> = {
  users: "users",
  albums: "albums",
  photos: "photos",
  orders: "orders",
  products: "products",
  kiosks: "kiosks",
  settings: "settings",
  destinations: "destinations",
  session_types: "session_types",
  packs: "packs",
  bookings: "bookings",
  photographer_ledger: "photographer_ledger",
  daily_objectives: "daily_objectives",
  expenses: "expenses",
  inventory: "inventory",
  equipment: "equipment",
  daily_resort_stats: "daily_resort_stats",
  photographer_performance: "photographer_performance",
};

export const JSON_COLUMNS: Record<string, string[]> = {
  users: ["workingHours"],
  albums: ["categories"],
  photos: ["manualEdits"],
  orders: ["items"],
  kiosks: ["settings"],
  settings: ["value"],
  destinations: ["featuresJSON"],
  packs: ["productsJSON"],
  daily_objectives: [],
  expenses: ["photographerIds"],
  inventory: [],
  equipment: [],
  photographer_performance: ["categories", "photos_made_themes"],
};

export const ALLOWED_COLUMNS: Record<string, string[]> = {
  users: [
    "id",
    "name",
    "email",
    "role",
    "status",
    "machine_id",
    "monthlyTarget",
    "dailyPhotoTarget",
    "payrollType",
    "monthlySalary",
    "commissionRate",
    "created_at",
    "updated_at",
  ],
  albums: [
    "id",
    "title",
    "date",
    "status",
    "photographerId",
    "eventType",
    "roomNumber",
    "source",
    "desk_id",
    "original_id",
    "created_at",
    "updated_at",
  ],
  orders: [
    "id",
    "date",
    "status",
    "clientName",
    "albumId",
    "totalAmount",
    "total",
    "desk_id",
    "original_id",
    "created_at",
    "updated_at",
  ],
  photos: [
    "id",
    "albumId",
    "url",
    "desk_id",
    "original_id",
    "created_at",
    "updated_at",
  ],
  products: [
    "id",
    "name",
    "price",
    "category",
    "status",
    "created_at",
    "updated_at",
  ],
  kiosks: ["id", "name", "status", "lastHeartbeat", "created_at", "updated_at"],
  settings: ["id", "key", "value", "created_at", "updated_at"],
  session_types: [
    "id",
    "name",
    "numberOfPhotos",
    "price",
    "created_at",
    "updated_at",
  ],
  packs: ["id", "name", "price", "description", "created_at", "updated_at"],
  bookings: [
    "id",
    "clientName",
    "bookingDate",
    "status",
    "photographerId",
    "destinationId",
    "created_at",
    "updated_at",
  ],
  photographer_ledger: [
    "id",
    "photographer_id",
    "order_id",
    "amount",
    "currency",
    "type",
    "rate_snapshot",
    "description",
    "desk_id",
    "original_id",
    "created_at",
    "updated_at",
  ],
  daily_objectives: [
    "id",
    "photographer_id",
    "date",
    "target",
    "status",
    "desk_id",
    "original_id",
    "created_at",
    "updated_at",
  ],
  expenses: [
    "id",
    "description",
    "amount",
    "category",
    "date",
    "photographerIds",
    "destinationId",
    "invoiceUrl",
    "desk_id",
    "original_id",
    "created_at",
    "updated_at",
  ],
  inventory: [
    "id",
    "name",
    "type",
    "current_count",
    "low_stock_threshold",
    "desk_id",
    "original_id",
    "created_at",
    "updated_at",
  ],
  equipment: [
    "id",
    "name",
    "type",
    "status",
    "assignedToPhotographerId",
    "destinationId",
    "purchaseDate",
    "warrantyExpiry",
    "serialNumber",
    "notes",
    "desk_id",
    "original_id",
    "created_at",
    "updated_at",
  ],
  daily_resort_stats: [
    "id",
    "desk_id",
    "date",
    "total_guests",
    "departures",
    "viewing_sessions",
    "daily_rent",
    "daily_labor",
    "updated_at",
  ],
  photographer_performance: [
    "id",
    "desk_id",
    "photographer_id",
    "date",
    "meetings_taken",
    "meetings_made",
    "categories",
    "income_simple",
    "income_multiple",
    "photos_made_themes",
    "total_session_seconds",
    "session_count",
    "updated_at",
  ],
};

export const LOGS_DIR = "./logs";
export const AUDIT_LOGS_DIR = "./logs/audit";
