import { logger } from '../utils/logger';
import { generateEd25519License, verifyEd25519License } from '@clickflash/licensing';

const KEY_PREFIX = 'CF-LIVE-';

export interface LicenseKeyData {
  key: string;
  deskId: string;
  plan: 'starter' | 'pro' | 'enterprise' | 'trial';
  maxMasters: number;
  expiresAt?: string;
  status: 'active' | 'expired' | 'revoked';
  createdAt: string;
}

export interface GenerateOptions {
  deskId: string;
  plan: 'starter' | 'pro' | 'enterprise' | 'trial';
  maxMasters: number;
  expiresDays?: number;
  count?: number;
  machineId: string;
}

export interface LicenseValidationResult {
  valid: boolean;
  plan?: string;
  maxMasters?: number;
  expiresAt?: string;
  error?: string;
}

export class LicenseService {
  private db?: any;
  private privateKeyB64?: string;
  private publicKeyB64?: string;

  constructor(db?: any, privateKeyB64?: string, publicKeyB64?: string) {
    this.db = db;
    this.privateKeyB64 = privateKeyB64;
    this.publicKeyB64 = publicKeyB64;
  }

  async generateLicenseKeys(options: GenerateOptions): Promise<LicenseKeyData[]> {
    const count = options.count || 1;
    const keys: LicenseKeyData[] = [];
    let expiresAtStr: string | undefined;

    if (options.expiresDays && options.expiresDays > 0) {
      const date = new Date();
      date.setDate(date.getDate() + options.expiresDays);
      expiresAtStr = date.toISOString();
    }

    const nowStr = new Date().toISOString();

    for (let i = 0; i < count; i++) {
      if (!this.privateKeyB64) {
        throw new Error('LICENSE_PRIVATE_KEY is required to generate licenses.');
      }
      const license = generateEd25519License({
        plan: options.plan,
        maxMasters: options.maxMasters,
        expiresDays: options.expiresDays || 365,
        machineId: options.machineId,
      }, this.privateKeyB64);

      const keyData: LicenseKeyData = {
        key: license.key,
        deskId: options.deskId,
        plan: options.plan,
        maxMasters: options.maxMasters,
        expiresAt: expiresAtStr,
        status: 'active',
        createdAt: nowStr
      };

      if (this.db) {
        try {
          if (typeof this.db.prepare === 'function') {
            // D1 binding
            await this.db.prepare(
              `INSERT INTO licenses (key, desk_id, plan, max_masters, status, expires_at, created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
            ).bind(
              keyData.key,
              keyData.deskId,
              keyData.plan,
              keyData.maxMasters,
              keyData.status,
              keyData.expiresAt || null,
              keyData.createdAt,
              keyData.createdAt
            ).run();
          } else if (typeof this.db.run === 'function') {
            // DatabaseManager wrapper
            await this.db.run(
              `INSERT INTO licenses (key, desk_id, plan, max_masters, status, expires_at, created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
              [
                keyData.key,
                keyData.deskId,
                keyData.plan,
                keyData.maxMasters,
                keyData.status,
                keyData.expiresAt || null,
                keyData.createdAt,
                keyData.createdAt
              ]
            );
          }
        } catch (err: any) {
          logger.error(`Failed to store generated license key: ${err.message}`);
          throw err;
        }
      }

      keys.push(keyData);
    }

    logger.info(`Generated ${keys.length} license key(s) for desk ${options.deskId} (${options.plan})`);
    return keys;
  }

  async validateLicenseKey(
    key: string,
    deskId?: string,
    machineId?: string,
  ): Promise<LicenseValidationResult> {
    if (!this.publicKeyB64) {
      return { valid: false, error: 'LICENSE_PUBLIC_KEY is not configured on server' };
    }
    if (!machineId) {
      return { valid: false, error: 'Machine ID is required for license validation' };
    }

    const result = verifyEd25519License(key, this.publicKeyB64, { expectedMachineId: machineId });
    if (!result.valid || !result.data) {
      return { valid: false, error: result.error || 'Invalid signature' };
    }
    if (!result.data.machineId || result.data.machineId !== machineId) {
      return { valid: false, error: 'License is not bound to this machine' };
    }

    // If we have database connection, check database records
    if (this.db) {
      try {
        let record: any = null;
        if (typeof this.db.prepare === 'function') {
          record = await this.db.prepare('SELECT * FROM licenses WHERE key = ? LIMIT 1').bind(key).first();
        } else if (typeof this.db.get === 'function') {
          record = await this.db.get('SELECT * FROM licenses WHERE key = ? LIMIT 1', [key]);
        }

        if (!record) {
          // AUTO-REGISTER OFFLINE LICENSES:
          // If the signature is valid, it was generated by our offline generator.
          // We seamlessly auto-register it into the D1 Database here.
          const newDeskId = deskId || result.data?.destinationId || 'UNASSIGNED';
          const newPlan = result.data?.plan || 'pro';
          const newMaxMasters = result.data?.maxMasters || 1;
          const newExpiresAt = result.data?.expiresAt || null;
          const newCreatedAt = result.data?.createdAt || new Date().toISOString();
          const newUpdatedAt = new Date().toISOString();

          if (typeof this.db.prepare === 'function') {
            await this.db.prepare(
              `INSERT INTO licenses (key, desk_id, plan, max_masters, status, expires_at, created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
            ).bind(
              key, newDeskId, newPlan, newMaxMasters, 'active', newExpiresAt, newCreatedAt, newUpdatedAt
            ).run();
          } else if (typeof this.db.run === 'function') {
            await this.db.run(
              `INSERT INTO licenses (key, desk_id, plan, max_masters, status, expires_at, created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
              [key, newDeskId, newPlan, newMaxMasters, 'active', newExpiresAt, newCreatedAt, newUpdatedAt]
            );
          }

          logger.info(`Auto-registered offline license key for desk: ${newDeskId}`);
          
          return {
            valid: true,
            plan: newPlan,
            maxMasters: newMaxMasters,
            expiresAt: newExpiresAt || undefined
          };
        }

        if (record.status !== 'active') {
          return { valid: false, error: `License key is ${record.status}` };
        }

        if (record.expires_at) {
          const expirationDate = new Date(record.expires_at).getTime();
          if (!isNaN(expirationDate) && expirationDate < Date.now()) {
            return { valid: false, error: 'License key has expired' };
          }
        }

        if (deskId && record.desk_id && record.desk_id !== deskId && record.desk_id !== 'UNASSIGNED') {
          return { valid: false, error: 'License key assigned to another desk' };
        }

        return {
          valid: true,
          plan: record.plan,
          maxMasters: record.max_masters || 1,
          expiresAt: record.expires_at || undefined
        };
      } catch (err: any) {
        logger.error(`Database error during license verification: ${err.message}`);
        return { valid: false, error: 'Database verification failed' };
      }
    }

    // Standalone validation has passed signature, expiry, and hardware binding.
    return {
      valid: true,
      plan: result.data?.plan || 'pro',
      maxMasters: result.data?.maxMasters || 5,
      expiresAt: result.data?.expiresAt || undefined
    };
  }
}
