name = "clickflash-website"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.preview]
name = "clickflash-website-preview"

[env.preview.vars]
NODE_ENV = "staging"
DEPLOY_ENV = "staging"

[env.production]
name = "clickflash-website"

[env.production.vars]
NODE_ENV = "production"
DEPLOY_ENV = "production"
