#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run typecheck and lint on changed files only (fast)
pnpm run security:tracked-private-key-filenames
npx turbo run typecheck lint --filter='...[HEAD~1]' --continue
